ALTER TABLE "WorkspaceSettings"
ADD COLUMN "shiftStart" TEXT NOT NULL DEFAULT '09:00',
ADD COLUMN "shiftEnd" TEXT NOT NULL DEFAULT '18:00',
ADD COLUMN "graceMinutes" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN "overtimeAfterMinutes" INTEGER NOT NULL DEFAULT 480;

ALTER TABLE "AttendanceRecord"
ADD COLUMN "overtimeHours" DECIMAL(4,2);
